smallrye/smallrye-fault-tolerance

implementation/src/main/resources/config.properties, pom.xml
properties file simplification
Signed-off-by: Antoine Sabot-Durand <antoine@sabot-durand.net>
=> Change config to released version

implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java, testsuite/basic/pom.xml, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/retry/CircuitBreakerRetryFallbackTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/retry/SuperCoolService.java, testsuite/basic/src/test/resources/logging.properties
=> HystrixCommandInterceptor - handle FailureType.SHORTCIRCUIT correctly

implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java
=> Fix HystrixCommandInterceptor.SYNC_CIRCUIT_BREAKER_KEY value

testsuite/basic/src/test/java/io/smallrye/faulttolerance/sync/ShakyServiceClient.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/sync/SyncCircuitBreakerDisabledTest.java
=> Make SyncCircuitBreakerDisabledTest more robust

docs/pom.xml, implementation/pom.xml, implementation/src/main/java/io/smallrye/faulttolerance/CommandListener.java, implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java, pom.xml, testsuite/basic/pom.xml, testsuite/basic/src/test/java/io/smallrye/faulttolerance/command/listener/CommandListenerTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/command/listener/HelloService.java, testsuite/pom.xml, testsuite/tck/pom.xml
=> Command listeners are invoked for any FT operation

implementation/src/main/java/io/smallrye/faulttolerance/DefaultFaultToleranceOperationProvider.java, implementation/src/main/java/io/smallrye/faulttolerance/FaultToleranceOperationProvider.java, implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java, implementation/src/main/java/io/smallrye/faulttolerance/HystrixExtension.java, implementation/src/main/java/io/smallrye/faulttolerance/config/BulkheadConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/CircuitBreakerConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/FallbackConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java, implementation/src/main/java/io/smallrye/faulttolerance/config/GenericConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/RetryConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/TimeoutConfig.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/FaultToleranceOperations.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/config/extension/ExtensionAnnotationTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/config/priority/ConfigParameterPriorityTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/metadata/BaseService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/metadata/HelloService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/metadata/RetryOnSubclassOverrideTest.java, testsuite/basic/src/test/resources/config.properties, testsuite/tck/src/test/resources/config.properties
=> Handle class hierarchies correctly

implementation/src/main/java/io/smallrye/faulttolerance/SynchronousCircuitBreaker.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/lastsuccess/CircuitBreakerLastSuccessOpensTest.java, testsuite/tck/pom.xml
- open the circuit if CLOSED and the last request in a rolling window
ends with success but failure threshold is reached
=> Fix SynchronousCircuitBreaker (#22)

implementation/pom.xml, implementation/src/main/java/io/smallrye/faulttolerance/DefaultFaultToleranceOperationProvider.java, implementation/src/main/java/io/smallrye/faulttolerance/HystrixExtension.java, implementation/src/main/java/io/smallrye/faulttolerance/SecurityActions.java, implementation/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java, implementation/src/test/java/io/smallrye/faulttolerance/config/InterfaceFaultToleranceOperationsTest.java
=> Make FaultToleranceOperation.isAnnotated() more robust

implementation/src/main/java/io/smallrye/faulttolerance/SynchronousCircuitBreaker.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/rollingwindow/CircuitBreakerRollingWindowTest.java
- i.e. whenever the requestVolumeThreshold is reached, even if the
status did not change
- resolves #28
=> Fix SynchronousCircuitBreaker - reset counters correctly

implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java, implementation/src/main/java/io/smallrye/faulttolerance/SynchronousCircuitBreaker.java, implementation/src/main/java/io/smallrye/faulttolerance/metrics/MetricsCollectorFactory.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/metrics/CircuitBreakerFailOnMetricsTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/metrics/PingService.java
=> fix circuit breaker metrics in case an exception isn't considered a failure

implementation/src/main/java/io/smallrye/faulttolerance/config/BulkheadConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/CircuitBreakerConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/FallbackConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/GenericConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/RetryConfig.java, implementation/src/main/java/io/smallrye/faulttolerance/config/SecurityActions.java, implementation/src/main/java/io/smallrye/faulttolerance/config/TimeoutConfig.java
=> GenericConfig - use methods from the annotation type

implementation/pom.xml, implementation/src/main/java/io/smallrye/faulttolerance/HystrixInitializer.java, implementation/src/main/java/io/smallrye/faulttolerance/tracing/TracingConcurrencyStrategy.java, implementation/src/main/java/io/smallrye/faulttolerance/tracing/TracingInstaller.java, pom.xml, testsuite/basic/pom.xml, testsuite/basic/src/test/java/io/smallrye/faulttolerance/tracing/Service.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/tracing/TracingContextPropagationTest.java
Added per @kenfinnigan request https://github.com/quarkusio/quarkus/pull/2038#issuecomment-483636456
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
=> Propagate tracing context

implementation/src/main/java/io/smallrye/faulttolerance/HystrixInitializer.java
=> tone down logging for Hystrix initialization

implementation/src/main/java/io/smallrye/faulttolerance/CompositeObservableCommand.java, implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java, implementation/src/main/java/io/smallrye/faulttolerance/tracing/TracingConcurrencyStrategy.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/fallback/AsyncHelloService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/fallback/AsynchronousCompletionStageFallbackTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/retry/AsyncHelloService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/retry/AsynchronousCompletionStageRetryTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/fallback/AsyncHelloService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/fallback/AsynchronousFallbackTest.java
=> fix @Asynchronous @Fallback with failed CompletionStage

pom.xml, release.sh
Also remove unneeded release.sh
=> Update to SmallRye parent 4

pom.xml, testsuite/tck/src/test/tck-suite.xml
=> update to MicroProfile Fault Tolerance 2.0.1

implementation/src/main/java/io/smallrye/faulttolerance/CompositeCommand.java, implementation/src/main/java/io/smallrye/faulttolerance/CompositeObservableCommand.java, implementation/src/main/java/io/smallrye/faulttolerance/metrics/BulkheadWaitRecorder.java, implementation/src/main/java/io/smallrye/faulttolerance/metrics/MetricsCollectorFactory.java, pom.xml, testsuite/basic/pom.xml, testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/metrics/CircuitBreakerFailOnMetricsTest.java, testsuite/tck/pom.xml
=> update to MP Metrics 2.0

docs/pom.xml, implementation/pom.xml, pom.xml, release/pom.xml, testsuite/basic/pom.xml, testsuite/pom.xml, testsuite/tck/pom.xml
=> Update to revised artifact/version scheme

implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java, implementation/src/main/java/io/smallrye/faulttolerance/RetryContext.java, implementation/src/main/java/io/smallrye/faulttolerance/metrics/MetricsCollectorFactory.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/retry/metrics/FallbackRetryMetricsTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/retry/metrics/MyService.java
=> fix retry & fallback metrics collection

implementation/pom.xml, pom.xml, testsuite/basic/pom.xml, testsuite/tck/pom.xml
=> update SmallRye Parent and move to Jakarta dependencies

pom.xml
The hdrHistogram was gone with hystrix.
=> Remove unused version.hdrHistogram property

api/pom.xml, api/src/main/java/io/smallrye/faulttolerance/api/CircuitBreakerState.java, api/src/main/java/io/smallrye/faulttolerance/api/CircuitBreakerStateChanged.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreaker.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreakerEvents.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java, implementation/fault-tolerance/pom.xml, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/CircuitBreakerStateObserver.java, pom.xml, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/circuitbreaker/state/CircuitBreakerStateTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/circuitbreaker/state/HelloService.java
=> provide a way to observe circuit breaker state

.gitignore, implementation/core/src/main/java/io/smallrye/faulttolerance/core/util/CompletionStages.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/exception/AsyncHelloService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/exception/AsynchronousCompletionStageExceptionHandlingTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/exception/HelloException.java
=> fix exception handling for @Asynchronous methods using CompletionStage

README.adoc, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/ExecutorProvider.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/sizing/AbstractAsyncThreadPoolSizingTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/sizing/AsyncThreadPoolSizingOldConfigTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/sizing/AsyncThreadPoolSizingTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/sizing/HelloService.java, testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/FaultToleranceApplicationArchiveProcessor.java
=> config rename

implementation/fault-tolerance/pom.xml, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MetricsCollectorFactory.java, pom.xml
Second part of the fix needed for https://github.com/quarkusio/quarkus/issues/12196
=> Make use of FunctionGaugeSupport if possible

.github/project.yml
=> release 4.3.2

README.adoc, implementation/core/src/main/java/io/smallrye/faulttolerance/core/Invocation.java, implementation/fault-tolerance/pom.xml, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/AsyncTypes.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/AsyncTypesConversion.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/StrategyCache.java, pom.xml, testsuite/basic/pom.xml, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/mutiny/HelloService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/mutiny/MutinyTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/rxjava/HelloService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/rxjava/RxjavaTest.java
=> add support for additional async types

doc/modules/ROOT/pages/integration/intro.adoc, implementation/context-propagation/pom.xml, implementation/fault-tolerance/pom.xml, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MetricsProvider.java, pom.xml
Also use corresponding SmallRye RC releases.
Resolves #283.
Resolves #294.
=> update MicroProfile Config to 2.0 and Metrics to 3.0

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MetricsProvider.java, pom.xml
This will be a requirement in MicroProfile Fault Tolerance 3.0.
=> make sure all possible metrics for given method are registered on first invocation

.github/workflows/build.yml, .github/workflows/release.yml, README.adoc, doc/antora-playbook.yml, doc/antora.yml, doc/modules/ROOT/pages/usage/extra.adoc
=> rename branch "master" to "main"

implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/FutureThreadPoolBulkhead.java
This fix is inspired by an earlier fix for similar issue in case of
`AsyncTimeout` and `Timeout`.
Here, we make sure that `Future.cancel`, as returned to the caller
by `FutureExecution`, doesn't attempt to cancel previously finished
bulkhead tasks. That would itself be harmless, but bulkhead task
cancellation may involve thread interruption. That would be a big
problem, because we might end up interrupting threads executing
foreign code.
=> fix FutureThreadPoolBulkhead in presence of retries

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FallbackConfig.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallbackmethod/parameterized/param/raw/ParameterizedAndRawFallbackMethod.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallbackmethod/parameterized/param/raw/ParameterizedAndRawFallbackMethodTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallbackmethod/parameterized/raw/param/RawAndParameterizedFallbackMethod.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallbackmethod/parameterized/raw/param/RawAndParameterizedFallbackMethodTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallbackmethod/parameterized/typearg/mismatch/TypeArgumentMismatchFallbackMethod.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallbackmethod/parameterized/typearg/mismatch/TypeArgumentMismatchFallbackMethodTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/util/WeldWithFaultToleranceExtension.java
=> fix fallback method return type assignability check

doc/modules/ROOT/pages/integration/intro.adoc, doc/modules/ROOT/pages/usage/extra.adoc, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceExtension.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/SpecCompatibility.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MetricsProvider.java, implementation/fault-tolerance/src/test/java/io/smallrye/faulttolerance/config/InterfaceFaultToleranceOperationsTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/noncompatible/NoncompatibleNonblockingAsyncTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/noncompatible/NoncompatibleNonblockingHelloService.java, testsuite/tck/pom.xml, testsuite/tck/src/test/tck-suite-non-compatible.xml
=> non-compatible mode for asynchrony

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/BlockingConfig.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/NonBlockingConfig.java
=> remove validation of method return types for @Blocking and @NonBlocking

.github/workflows/build.yml, pom.xml
=> update Weld and reenable Java 17 on CI

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FallbackConfig.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FallbackValidation.java, implementation/fault-tolerance/src/test/java/io/smallrye/faulttolerance/config/FallbackValidationTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/handler/primitive/MyIntFallbackHandler.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/handler/primitive/MyService.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/handler/primitive/MyVoidFallbackHandler.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/handler/primitive/PrimitiveFallbackHandlerTest.java
=> allow defining a FallbackHandler for methods that return primitive types

api/src/main/java/io/smallrye/faulttolerance/api/FaultTolerance.java, api/src/main/java/io/smallrye/faulttolerance/api/FaultToleranceSpi.java, api/src/main/java/io/smallrye/faulttolerance/api/FaultToleranceSpiAccess.java, doc/modules/ROOT/nav.adoc, doc/modules/ROOT/pages/integration/async-types.adoc, doc/modules/ROOT/pages/integration/intro.adoc, doc/modules/ROOT/pages/integration/programmatic-api.adoc, doc/modules/ROOT/pages/usage/extra.adoc, doc/modules/ROOT/pages/usage/programmatic-api.adoc, implementation/core/src/main/java/io/smallrye/faulttolerance/core/async/types/AsyncTypes.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/CdiFaultTolerance.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/CdiFaultToleranceSpi.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/SpecCompatibility.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/AsyncValidation.java, implementation/mutiny/pom.xml, implementation/mutiny/src/main/java/io/smallrye/faulttolerance/mutiny/api/MutinyFaultTolerance.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyBulkheadTest.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyCircuitBreakerTest.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyFallbackTest.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyPassthroughTest.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyResubscriptionTest.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyRetryTest.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyTimeoutTest.java, implementation/standalone/pom.xml, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/StandaloneFaultTolerance.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/StandaloneFaultToleranceSpi.java, implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneTimeoutAsyncTest.java, implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneTimeoutTest.java
=> add a Mutiny entrypoint to the programmatic API

api/src/main/java/io/smallrye/faulttolerance/api/FaultTolerance.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/CdiFaultTolerance.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/StandaloneFaultTolerance.java
=> use proper descriptions of fault tolerance strategies

implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/BuilderEagerDependencies.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/BuilderLazyDependencies.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/LazyFaultTolerance.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/CdiFaultToleranceSpi.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceExtension.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/StandaloneFaultToleranceSpi.java
=> instantiate programmatically created FaultTolerance lazily

.github/workflows/build.yml, pom.xml
=> enforce build with Java 9+

implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/BulkheadBase.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/BulkheadLogger.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/CompletionStageThreadPoolBulkhead.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/FutureThreadPoolBulkhead.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/SemaphoreBulkhead.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreaker.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreakerLogger.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/fallback/CompletionStageFallback.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/fallback/Fallback.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/Retry.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/CompletionStageTimeout.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/Timeout.java
=> Promote interesting logging to debug level and add description

implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/Retry.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/CompletionStageTimeout.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/Timeout.java
=> Add more information to Retry/Timeout logs

doc/modules/ROOT/pages/usage/basic.adoc, doc/modules/ROOT/pages/usage/extra.adoc, implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/MetricsCollector.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/MetricsRecorder.java, implementation/core/src/test/java/io/smallrye/faulttolerance/core/metrics/GeneralMetricsTest.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MetricConstants.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicroProfileMetricsProvider.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicrometerProvider.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/metrics/CircuitBreakerFailOnMetricsTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/metrics/PingService.java
=> expose current circuit breaker state through metrics

api/src/main/java/io/smallrye/faulttolerance/api/FaultToleranceSpiAccess.java, doc/modules/ROOT/pages/integration/metrics.adoc
=> fix lookup of FaultToleranceSpi when multiple implementations are present

doc/modules/ROOT/pages/integration/programmatic-api.adoc, doc/modules/ROOT/pages/reference/programmatic-api.adoc, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/ThreadTimer.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/Timer.java, implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/TestTimer.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/Configuration.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/DefaultConfiguration.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/EagerDependencies.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/LazyDependencies.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/StandaloneFaultTolerance.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/StandaloneFaultToleranceSpi.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/TimerAccess.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/TimerAccessImpl.java
=> add integration API to the standalone implementation

implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/Timeout.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/TimeoutExecution.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/ThreadTimer.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/TimerLogger.java, implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/RealWorldCompletionStageTimeoutTest.java, implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/TimerTimeoutWatcherTest.java, implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/ThreadTimerStressTest.java, implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/ThreadTimerTest.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/ExecutorHolder.java, implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/LazyDependencies.java
=> improve memory footprint of the timer

implementation/core/src/main/java/io/smallrye/faulttolerance/core/InvocationContext.java
1) in tests data.size() is never > 2: set initialCapacity from 16 to 4 
2) don't do extra work for absent eventHandler
=> InvocationContext micro optimizations

doc/modules/ROOT/pages/reference/rate-limit.adoc
=> Improve reference documentation for rate limit

implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/LazyFaultTolerance.java
Replace https://github.com/smallrye/smallrye-fault-tolerance/pull/1034
=> Replace synchronized block with ReentrantLock in LazyFaultTolerance

api/src/main/java/io/smallrye/faulttolerance/api/FaultTolerance.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/LazyFaultTolerance.java, implementation/mutiny/src/test/java/io/smallrye/faulttolerance/mutiny/test/MutinyFaultToleranceCastTest.java, implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneFaultToleranceCastAsyncTest.java, implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneFaultToleranceCastTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiFaultToleranceCopyAsyncTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiFaultToleranceCopyTest.java
=> add FaultTolerance.cast() and castAsync()

implementation/autoconfig/core/src/main/java/io/smallrye/faulttolerance/autoconfig/FaultToleranceMethod.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/DefaultFaultToleranceOperationProvider.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceExtension.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/BeforeRetryConfig.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FallbackConfig.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceMethods.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/KotlinSupport.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/SecurityActions.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/BeforeRetryMethod.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/FallbackMethodCandidates.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/KotlinSupport.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/StrategyCache.java
=> static resolution of FT methods (@Fallback.fallbackMethod, @BeforeRetry.methodName)

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/CompoundMetricsProvider.java
=> fix dynamic lookup in CompoundMetricsProvider

implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/GuardImpl.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/TypedGuardImpl.java, implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/Bulkhead.java, implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/BulkheadConfig.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/bulkhead/capacity/overflow/BulkheadCapacityOverflowTest.java, testsuite/basic/src/test/java/io/smallrye/faulttolerance/bulkhead/capacity/overflow/MyService.java
=> detect bulkhead capacity overflow
