implementation/src/main/java/io/smallrye/faulttolerance/CommandListener.java
implementation/src/main/java/io/smallrye/faulttolerance/CommandListenersProvider.java
implementation/src/main/java/io/smallrye/faulttolerance/DefaultCommandListenersProvider.java
implementation/src/main/java/io/smallrye/faulttolerance/DefaultFallbackHandlerProvider.java
implementation/src/main/java/io/smallrye/faulttolerance/DefaultFaultToleranceOperationProvider.java
implementation/src/main/java/io/smallrye/faulttolerance/DefaultHystrixConcurrencyStrategy.java
implementation/src/main/java/io/smallrye/faulttolerance/FaultToleranceOperationProvider.java
implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java
implementation/src/main/java/io/smallrye/faulttolerance/HystrixExtension.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/command/listener/CommandListenerTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/command/listener/WeldCommandListenersProvider.java

- also introduce CommandListenersProvider to work around limitation in
CDI API - we need to destroy dependent CommandListener instances after
execution is finished (this will allow integrators to leverage
non-portable APIs)

Add CommandListener.getPriority()

---

implementation/src/main/java/io/smallrye/faulttolerance/HystrixCommandInterceptor.java
implementation/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java

handle MP_Fault_Tolerance_NonFallback_Enabled properly

---

testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/FaultToleranceApplicationArchiveProcessor.java
testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/RequestContextCommandListener.java

This is a copied version from what TT uses; enabled only in TCKs.
Let's see if CI likes it :)

Add request context activator into TCKs.

---

pom.xml
testsuite/tck/src/test/tck-suite.xml

- Exclude failing MP FT TCK tests that have binary incompatibility with MP Metrics API class

Update to MP Metrics 2.1.0 and SRye Metrics 2.2.0

---

testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/FaultToleranceApplicationArchiveProcessor.java

See https://github.com/eclipse/microprofile-fault-tolerance/pull/495
for more info. When that PR is merged, this commit shall be reverted.

workaround for MP FT TCK issue in TimeoutMetricTest

---

implementation/context-propagation/src/main/java/io/smallrye/faulttolerance/propagation/ContextPropagatingScheduledExecutorService.java
implementation/context-propagation/src/main/java/io/smallrye/faulttolerance/propagation/ContextPropagationExecutorFactory.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/CompletionStageTimeout.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/CompletionStageTimeoutTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/RealWorldCompletionStageTimeoutTest.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java
pom.xml
testsuite/integration/pom.xml
testsuite/integration/src/test/java/io/smallrye/faulttolerance/tracing/TracingContextPropagationTest.java
testsuite/integration/src/test/java/io/smallrye/faulttolerance/tracing/stress/Service.java
testsuite/integration/src/test/java/io/smallrye/faulttolerance/tracing/stress/TracingContextPropagationStressTest.java

This commit fixes asynchronous (`CompletionStage`-based) timeout
threading behavior. Originally, when timeout occured, the timeout
watcher thread would complete the `CompletionStage`, which would
immediately result in subsequent tasks ("dependent stages") being
run. They would, however, run on the timeout watcher thread, which
is wrong. In this commit, we make sure that the `CompletionStage`
is completed on a thread from the original thread pool.
To make this all work together with Context Propagation, this commit
also lets the timeout watcher thread pool propagate contexts. This
happens twice. First, when the timeout action is being executed,
context from original thread is propagated to the timeout watcher
thread. Second, when the `CompletionStage` is completed in the
original thread …

fix CompletionStageTimeout threading

---

implementation/fault-tolerance/pom.xml
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceExtension.java
implementation/fault-tolerance/src/main/resources/smallrye-fault-tolerance.properties
implementation/pom.xml

This commit also removes the old Java 9 compilation hack.
The SmallRye Parent POM includes a much better solution.

log SmallRye Fault Tolerance version during startup

---

implementation/context-propagation/src/main/java/io/smallrye/faulttolerance/propagation/ContextPropagationExecutorFactory.java

Starting with version 1.0.16, SmallRye Context Propagation no longer
creates a new thread pool for `ManagedExecutor.builder().build()`
when a default thread pool is set (which it is e.g. in Quarkus).
Currently, SmallRye Fault Tolerance requires new thread pools that
it can control, so this commit uses the SmallRye Context Propagation
specific API to force thread pool creation.
This unfortunately means that SmallRye Fault Tolerance is tied to
SmallRye Context Propagation. It was before, too, but that was
an accident and could be easily removed. It is an intention now.
This will become obsolete in a future version, which is rewritten
to only ever use a single thread pool, provided by the integrator.
In other words, this is a temporary workaround.

force creating thread pools with SmallRye Context Propagation

---

implementation/context-propagation/src/main/java/io/smallrye/faulttolerance/propagation/ContextPropagationRequestContextControllerProvider.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/Timer.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceExtension.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/RequestContextIntegration.java

In addition, some fields are no longer `static` to prevent possible
issues in modular classloading environment.

move ServiceLoader calls out of common code path

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/timeout/CompletionStageTimeout.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreakerTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/fallback/CompletionStageFallbackTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetryTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/CompletionStageTimeoutTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/RealWorldCompletionStageTimeoutTest.java

The `CompletionStageTimeout` strategy used `CompletableFuture.cancel`
in an attempt to interrupt the executing thread. That is wrong,
as `CompletionStage` (and hence also `CompletableFuture`) doesn't
support cancellation. The `cancel` method only completes the future
with an exception, but doesn't (and can't) interrupt anything.
The code is now removed, and unit tests are adjusted to always
run `CompletionStage` strategies on an extra thread. (And not only
`CompletionStageTimeout` tests, but all `CompletionStage` tests.)
Resolves #213.

remove incorrect CompletableFuture.cancel from CompletionStageTimeout

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreaker.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/Timer.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/TimerTask.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/circuit/breaker/failon/halfopen/AsyncHelloService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/circuit/breaker/failon/halfopen/CompletionStageCircuitBreakerFailOnHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/halfopen/CircuitBreakerFailOnHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/halfopen/HelloService.java

Previously, when the circuit breaker was half-open, it would always
consider exceptions as failures. This is wrong, the `failOn` and
`skipOn` configuration needs to be considered, just like when closed.
This commit fixes that, adds tests, and also adds some missing
trace logging to `CompletionStageCircuitBreaker`.
Fixes #320

fix circuit breaker exception handling in half-open

---

implementation/core/pom.xml
implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreaker.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/util/party/Party.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/util/party/PartyImpl.java
pom.xml
testsuite/basic/pom.xml
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/circuit/breaker/failon/halfopen/CompletionStageCircuitBreakerFailOnHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/circuit/breaker/halfopen/AsyncHelloService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/circuit/breaker/halfopen/CompletionStageCircuitBreakerHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/failon/halfopen/CircuitBreakerFailOnHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/halfopen/CircuitBreakerHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/halfopen/HelloService.java
testsuite/basic/src/test/resources/logging.properties
testsuite/integration/src/test/resources/logging.properties
testsuite/tck/src/test/resources/logging.properties

Previously, circuit breakers in the half-open state would let
all invocations go through. In case of any failure, it would
move back to open, and in case of a configured number of consecutive
successes, it would move to closed.
This is fine and passes the TCK, but under high load, this can
cause a thundering herd problem on the guarded service.
A better solution, implemented by this commit, is: in half-open,
only allow the first `successThreshold` invocations to go through
(also known as "probe invocations"), and reject the rest. If any
of those probe invocations fail, move back to open; if all of them
succeed, move to closed.
Fixes #319

improve circuit breaker to reject excess attempts in half-open

---

doc/modules/ROOT/pages/integration/event-loop.adoc
pom.xml

Also bump Vert.x to latest micro release.

document Vert.x version for the event loop integration

---

.github/maven-ci-settings.xml
.github/workflows/build.yml
.github/workflows/release.yml

This is to improve CI stability. Maven Central often has short outages
that cause CI failures. Those are usually fixed simply by rerunning
the jobs.

use Google Maven Central mirror as an additional repository in all CI jobs

---

.github/dependabot.yml

This configuration got carried over when dependabot suggested migration from dependabot-preview but it didn't account that this dependency has been removed completely.

Remove non-existent dependency from dependabot configuration

---

implementation/fault-tolerance/pom.xml
implementation/vertx/pom.xml
pom.xml

The `smallrye-build-parent` POM only includes stuff related to
building (including MR JARs) and releasing. It doesn't manage
any dependencies. This lets us fully manage dependencies ourselves,
resulting in more control and more predictable builds.

use smallrye-build-parent instead of smallrye-parent

---

implementation/core/pom.xml
implementation/core/src/test/java/io/smallrye/faulttolerance/core/bulkhead/CompletionStageThreadPoolBulkheadTest.java

Replaced Thread.sleep calls with Awaitility and small clean ups in CompletionStageThreadPoolBulkheadTest

Replaced Thread.sleep calls with Awaitility in CompletionStageThreadPoolBulkheadTest

---

doc/modules/ROOT/pages/integration/intro.adoc
doc/modules/ROOT/pages/usage/extra.adoc
implementation/core/src/main/java/io/smallrye/faulttolerance/core/async/types/AsyncTypeConverter.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/async/types/AsyncTypesConversion.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/async/types/AsyncTypesLogger.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/async/types/CompletionStageConverter.java
implementation/core/src/main/resources/META-INF/services/io.smallrye.faulttolerance.core.async.types.AsyncTypeConverter
implementation/fault-tolerance/pom.xml
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/AsyncTypes.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/AsyncValidation.java
implementation/mutiny/pom.xml
implementation/mutiny/src/main/java/io/smallrye/faulttolerance/mutiny/impl/UniConverter.java
implementation/mutiny/src/main/resources/META-INF/services/io.smallrye.faulttolerance.core.async.types.AsyncTypeConverter
implementation/pom.xml
implementation/rxjava3/pom.xml
implementation/rxjava3/src/main/java/io/smallrye/faulttolerance/rxjava3/impl/CompletableConverter.java
implementation/rxjava3/src/main/java/io/smallrye/faulttolerance/rxjava3/impl/MaybeConverter.java
implementation/rxjava3/src/main/java/io/smallrye/faulttolerance/rxjava3/impl/SingleConverter.java
implementation/rxjava3/src/main/resources/META-INF/services/io.smallrye.faulttolerance.core.async.types.AsyncTypeConverter
implementation/vertx/pom.xml
pom.xml
testsuite/basic/pom.xml
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/mutiny/resubscription/HelloService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/mutiny/resubscription/MutinyResubscriptionTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/rxjava/resubscription/HelloService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/types/rxjava/resubscription/RxjavaResubscriptionTest.java

This commit moves from SmallRye Reactive Converters to a built-in
async type conversion facility. This new conversion library enforces
that the async type is not created from a `CompletionStage` (which
is eager and hence already running), but from a `Supplier` of
`CompletionStage`. Hence, lazy async types may be created as truly
lazy, and if they allow resubscription, that works properly.
Tests for resubscription are added both for Mutiny and RxJava 3.
SmallRye Reactive Converters supported Mutiny, all RxJava major
versions, and Reactor. The built-in library supports Mutiny and
RxJava 3, which I believe is enough. Adding support for Reactor
would be trivial, but doesn't seem necessary at this point.
Resolves #504

revamp async types support

---

pom.xml
testsuite/basic/pom.xml
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/noncompatible/NoncompatibleNonblockingAsyncTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/sizing/AsyncThreadPoolSizingOldConfigTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/sizing/AsyncThreadPoolSizingTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/maintenance/CircuitBreakerMaintenanceInteroperabilityTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/config/priority/ConfigParameterPriorityTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/fallback/causechain/FallbackWithExceptionCauseChainTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiSkipFaultToleranceTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/retry/backoff/exponential/config/ConfiguredExponentialBackoffRetryTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/util/WithSystemProperty.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/util/WithSystemPropertyExtension.java
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/bulkhead/KotlinBulkheadTest.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/circuitbreaker/KotlinCircuitBreakerTest.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/retry/KotlinRetryTest.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/timeout/KotlinTimeoutTest.kt
testsuite/integration/pom.xml

The `@SetSystemProprety` annotation/extension from JUnit Pioneer
was used on a couple places to change MP Config configuration.
In version 1.7.0, JUnit Pioneer makes a breaking change and
class-level annotations are now handled as method-level annotations
present on all methods, which leads to some tests failing
because MP Config configuration isn't changed early enough.
(An implicit assumption is made that class-level annotations
roughly correspond to the `{Before,After}AllCallback` extension
points of JUnit Jupiter, while method-level annotations roughly
correspond to the `{Before,After}EachCallback` extension points.
This assumption is, in my opinion, rather intuitive.)
In this commit, `@SetSystemProperty` from JUnit Pioneer is replaced
with our own `@WithSystemProperty` that behaves …

get rid of JUnit Pioneer

---

testsuite/tck/pom.xml
testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/FaultToleranceExtension.java
testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/LoggingTestListener.java
testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/RetryTckOnMac.java

This commit also adds TCK progress logging in the form of a TestNG
listener, enabled in the POM.
Fixes #448

work around RetryTest.testClassLevelRetryMaxDuration TCK failures on macOS

---

doc/modules/ROOT/pages/integration/intro.adoc
implementation/autoconfig/core/src/main/java/io/smallrye/faulttolerance/autoconfig/Config.java
implementation/autoconfig/processor/src/main/java/io/smallrye/faulttolerance/autoconfig/processor/AutoConfigProcessor.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java

This commit:
- allows immediate materialization of fault tolerace configuration;
- provides access to some previously hidden configuration objects.
Additionally, it adds a missing item in the integration documentation
table of contents.

Allow outside visibility into effective fault tolerance configuration

---

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicroProfileMetricsProvider.java

Per the MP Metrics specification, if a `Metadata` object is constructed without the metric type and then used to create a metric of a specific type using `MetricRegistry` methods (such as `counter` or `gauge`), the metric type is set automatically. Since the `MicroProfileMetricsProvider` always uses the specific `MetricRegistry` methods (and never the generic method `register`), setting the metric type in `Metadata` is not necessary.
Further, MP Metrics 5.0 removes the notion of `MetricType` altogether, but the rest of the `Metadata` API remains intact. This commit makes porting SmallRye Fault Tolerance to MP Metrics 5.0 much easier.

avoid explicitly setting metric type for MicroProfile Metrics

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreaker.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/ThreadTimer.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/Timer.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/TimerTask.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/circuit/breaker/CircuitBreakerTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreakerTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/circuit/breaker/FutureCircuitBreakerTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/composition/Strategies.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/RealWorldCompletionStageTimeoutTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/TimerTimeoutWatcherTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/TestTimer.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/ThreadTimerStressTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/ThreadTimerTest.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/ExecutorHolder.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java
implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/StandaloneFaultToleranceSpi.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/circuit/breaker/timer/halfopen/AsyncHelloService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/circuit/breaker/timer/halfopen/CompletionStageCircuitBreakerTimerHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/timer/halfopen/CircuitBreakerTimerHalfOpenTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/circuitbreaker/timer/halfopen/HelloService.java

The circuit breaker implementation used to perform state transitions only during invocations (that is, synchronously). This is easy to implement and doesn't affect correctness of the circuit breaker algorithm, so there's nothing wrong with it.
However, SmallRye Fault Tolerance allows external observation of the circuit breaker state. With the existing implementation of state transitions only during invocations, such external observations would be correct when moving from closed to open and from half-open to closed (because these transitions are defined to happen as a result of an invocation), but would _not_ be correct when moving from open to half-open (which is defined to happen after certain amount of time, regardless of invocations).
For example, if the circuit breaker is configured …

fix circuit breaker state transitions

---

doc/modules/ROOT/pages/reference/asynchronous.adoc
doc/modules/ROOT/pages/reference/bulkhead.adoc
doc/modules/ROOT/pages/reference/circuit-breaker.adoc
doc/modules/ROOT/pages/reference/fallback.adoc
doc/modules/ROOT/pages/reference/rate-limit.adoc
doc/modules/ROOT/pages/reference/retry.adoc
doc/modules/ROOT/pages/reference/timeout.adoc

This commit puts the _Interactions with Other Strategies_ sections right after the _Description_ sections in all reference guides for fault tolerance strategies.
Related to #823

reorder reference guides

---

implementation/autoconfig/core/src/main/java/io/smallrye/faulttolerance/autoconfig/KotlinSupport.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/KotlinSupport.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/FallbackMethod.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/FallbackMethodCandidates.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/KotlinSupport.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/SecurityActions.java
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/fallback/KotlinFallbackTest.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/fallback/MyService.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/fallback/invalid/KotlinInvalidFallbackTest.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/fallback/invalid/MyService.kt

This commit fixes the algorithm that finds fallback methods in case of Kotlin `suspend` functions that declare an additional exception parameter. This additional parameter must be at the very end of the function signature, with the exception of Kotlin `suspend` functions, where the very last parameter must be the Kotlin `Continuation`. In this case, the exception parameter must be the _second last_.
Fixes #828

fix searching for fallback methods

---

api/src/main/java/io/smallrye/faulttolerance/api/FaultTolerance.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java

FaultToleranceImpl.BuilderImpl.withThreadOffload
withThreadOffload(false) must be allowed in any mode (sync or async)

FaultToleranceImpl.BuilderImpl.withThreadOffload: allow disabling in sync mode

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/util/Preconditions.java

• check T +long,int → remove unnecessary boxing/unboxing 
• todo checkNotNull → Objects.requireNonNull (can be inlined)

Preconditions optimizations

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/util/Durations.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/util/DurationsTest.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/FaultToleranceOperation.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/RetryConfig.java

See java.lang.Math#multiplyExact(long, long)
ArithmeticException can be thrown
and temporary Duration objects are created

prevent arithmetic overflow and reduce allocations in time conversions

---

api/src/main/java/io/smallrye/faulttolerance/api/AsynchronousNonBlocking.java
api/src/main/java/io/smallrye/faulttolerance/api/FaultTolerance.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/async/RememberEventLoop.java
implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneThreadOffloadTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiThreadOffloadTest.java

This method allows configuring the executor to use for thread offloads of actions guarded by the built `FaultTolerance` instance.
Fixes #988

add FaultTolerance.Builder.withThreadOffloadExecutor()

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/LazyFaultTolerance.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/invocation/AsyncSupport.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/invocation/CompletionStageSupport.java
implementation/kotlin/src/main/kotlin/io/smallrye/faulttolerance/kotlin/impl/CoroutineSupport.kt
implementation/mutiny/src/main/java/io/smallrye/faulttolerance/mutiny/impl/UniSupport.java
implementation/rxjava3/src/main/java/io/smallrye/faulttolerance/rxjava3/impl/CompletableSupport.java
implementation/rxjava3/src/main/java/io/smallrye/faulttolerance/rxjava3/impl/MaybeSupport.java
implementation/rxjava3/src/main/java/io/smallrye/faulttolerance/rxjava3/impl/SingleSupport.java
implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneMetricsTimerTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiMetricsTimerTest.java

The previous implementation of `FaultTolerance.run()` simply delegated to `call()` with a `Callable` that produces `null`. In the async mode, the `null` is treated as a valid `CompletionStage`, which immediately results in a NPE. That NPE is subsequently caught and transformed into a failed `CompletionStage`, but it's better to not throw it at all.
To be able to do this, the internal SPI `AsyncSupport` gains a new method that is able to create an already complete instance of the async type.

fix FaultTolerance.run() causing a NPE in async mode

---

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/internal/SecurityActions.java

The previous implementation considered all superclasses, but only implemented interfaces of the bean class. The new implementation also considers implemented interfaces of all superclasses and superinterfaces.

fix method search in SecurityActions.findMethod()

---

doc/modules/ROOT/pages/reference/metrics.adoc
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/ThreadTimer.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/Timer.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/timer/TimerLogger.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/RealWorldCompletionStageTimeoutTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timeout/TestTimer.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/TestTimer.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/ThreadTimerStressTest.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/timer/ThreadTimerTest.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/ExecutorHolder.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicroProfileMetricsProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicrometerProvider.java
implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/LazyDependencies.java
implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/MicrometerAdapter.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiMetricsTimerTest.java

This is for multi-deployment environments, like WildFly, where multiple applications may exist and each will have its own timer.
Fixes #1047

make ThreadTimer not singleton again

---

api/src/main/java/io/smallrye/faulttolerance/api/AsynchronousNonBlocking.java
doc/antora.yml
doc/modules/ROOT/pages/integration/metrics.adoc
doc/modules/ROOT/pages/integration/programmatic-api.adoc
doc/modules/ROOT/pages/reference/bulkhead.adoc
doc/modules/ROOT/pages/reference/circuit-breaker.adoc
doc/modules/ROOT/pages/reference/metrics.adoc
doc/modules/ROOT/pages/reference/programmatic-api.adoc
doc/modules/ROOT/pages/reference/rate-limit.adoc
doc/modules/ROOT/pages/reference/retry.adoc
doc/modules/ROOT/pages/reference/timeout.adoc
implementation/core/pom.xml
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/OpenTelemetryRecorder.java
implementation/fault-tolerance/pom.xml
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceExtension.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/CompoundMetricsProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MetricsIntegration.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicroProfileMetricsProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/OpenTelemetryProvider.java
implementation/standalone/pom.xml
implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/LazyDependencies.java
implementation/standalone/src/main/java/io/smallrye/faulttolerance/standalone/OpenTelemetryAdapter.java
pom.xml
testsuite/integration/pom.xml
testsuite/tck/pom.xml
testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/FaultToleranceExtension.java
testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/ForceOtelBean.java
testsuite/tck/src/test/java/io/smallrye/faulttolerance/tck/OtelConfigExtension.java
testsuite/tck/src/test/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension

Add OpenTelemetry support

---

api/src/main/java/io/smallrye/faulttolerance/api/ApplyFaultTolerance.java
doc/modules/ROOT/pages/reference/reusable.adoc
implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/LazyFaultTolerance.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/DelegatingCompletionStageMetricsCollector.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/DelegatingMeteredOperation.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/DelegatingMetricsCollector.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/MeteredOperationName.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/async/completionstage/metrics/MyFaultTolerance.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/async/completionstage/metrics/MyService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/async/completionstage/metrics/ReuseAsyncCompletionStageMetricsTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/async/uni/metrics/MyFaultTolerance.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/async/uni/metrics/MyService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/async/uni/metrics/ReuseAsyncUniMetricsTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/sync/metrics/MyFaultTolerance.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/sync/metrics/MyService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/sync/metrics/ReuseSyncMetricsTest.java
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/reuse/metrics/MyFaultTolerance.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/reuse/metrics/MyService.kt
testsuite/basic/src/test/kotlin/io/smallrye/faulttolerance/kotlin/reuse/metrics/ReuseKotlinMetricsTest.kt

This commit separates metrics of `@ApplyFaultTolerance` methods, so that each method has its own metrics yet they all share the same state.
Fixes #1060

separate metrics of @ApplyFaultTolerance for each method

---

api/src/main/java/io/smallrye/faulttolerance/api/FaultTolerance.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/FutureThreadPoolBulkhead.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/SemaphoreThreadPoolBulkhead.java

This method enables bulkhead queueing for synchronous actions executed on virtual threads. The implementation is a simple two-semaphores bulkhead, which has in fact already existed as `FutureThreadPoolBulkhead`. This commit generalizes that class and leaves `FutureThreadPoolBulkhead` as a special case, nearly empty, for guarding asynchronous actions returning `Future<V>`.
Fixes #987
Closes #1015

add FaultTolerance.BulkheadBuilder.enableVirtualThreadsQueueing()

---

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/CompoundMetricsProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicroProfileMetricsProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicrometerProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/OpenTelemetryProvider.java

This commit turns injection of metric registries in metric providers into a lazy variant (`Provider<>`), and turns field injection into constructor injection. This is all to make `CompoundMetricsProvider` work properly in case some of the metric providers actually cannot function properly, because the respective dependencies do not exist.

Make metric providers properly lazy

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/retry/beforeretry/AsyncHelloService.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/async/compstage/retry/beforeretry/AsynchronousCompletionStageRetryTest.java

The async implementation of retry had a bug in that it attempted to call the before retry action even before the initial attempt. This is wrong, plus it leads to an exception in the constructor of `FailureContext`. This commit fixes that bug and adds missing tests.

Fix asynchronous @BeforeRetry

---

doc/modules/ROOT/pages/reference/metrics.adoc
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/CompoundMetricsProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/Constants.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicroProfileMetricsProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MicrometerProvider.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/OpenTelemetryProvider.java

add ability to disable individual metric providers

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/bulkhead/Bulkhead.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/mixed/bulkhead/MixedReuseBulkheadTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/mixed/bulkhead/MyFaultTolerance.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/reuse/mixed/bulkhead/MyService.java

The bulkhead implementation for the synchronous case didn't acquire the capacity semaphore, it only used the work semaphore. This is wrong in case multiple kinds of the bulkhead are used at the same time, where the bulkhead might already be full due to synchronous invocations, but an asynchronous invocation could still be accepted into the bulkhead because the capacity semaphore is not in the right state.
This commit fixes that by changing the synchronous implementation to also use the capacity semaphore, in addition to the usage of the work semaphore.

fix bulkhead in case multiple kinds are used at the same time

---

implementation/core/src/main/java/io/smallrye/faulttolerance/core/fallback/ThreadOffloadFallbackFunction.java
implementation/vertx/src/main/java/io/smallrye/faulttolerance/vertx/VertxEventLoop.java

The Vert.x event loop integration used to assume that all Vert.x threads always have a current context associated. That isn't necessarily true, especially in case of worker threads, where a task can easily be submitted to the worker thread pool as an ordinary thread pool, outside of a Vert.x context. In that case, the thread cannot be treated as an event loop.
Additionally, this commit synchronizes the thread offload fallback function with the thread offload strategy, so that if there's an event loop remembered, the fallback is executed on it instead of the main executor.

fix the Vert.x event loop integration

---

api/src/main/java/io/smallrye/faulttolerance/api/Guard.java
api/src/main/java/io/smallrye/faulttolerance/api/TypedGuard.java
doc/modules/ROOT/pages/reference/programmatic-api.adoc
implementation/apiimpl/src/main/java/io/smallrye/faulttolerance/apiimpl/BasicMeteredOperationImpl.java
implementation/apiimpl/src/main/java/io/smallrye/faulttolerance/apiimpl/FaultToleranceImpl.java
implementation/apiimpl/src/main/java/io/smallrye/faulttolerance/apiimpl/GuardImpl.java
implementation/apiimpl/src/main/java/io/smallrye/faulttolerance/apiimpl/TypedGuardImpl.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/DelegatingMeteredOperation.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/DelegatingMetricsCollector.java
implementation/core/src/main/java/io/smallrye/faulttolerance/core/metrics/MeteredOperation.java
implementation/core/src/test/java/io/smallrye/faulttolerance/core/metrics/GeneralMetricsTest.java
implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/CdiMeteredOperationImpl.java
implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneMetricsTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiMetricsTest.java

The issue is that a random UUID is used as a value of the metrics tag `method` if the user doesn't set a description on `Guard` / `TypedGuard` and doesn't use them with `@ApplyGuard`. These values are always held in memory, so in case more and more `Guard` / `TypedGuard` objects without description are created, more and more memory is held.
The fix is relatively simple: in case no description is set (and a random UUID should be used), no metrics are emitted. This is technically a breaking change, but it's better to require users to explicitly state the value of the metrics tag than to leak memory.
(The same applies to the old `FaultTolerance` and `@ApplyFaultTolerance` API.)
Fixes #1108

fix memory leak in metrics

---

api/src/main/java/io/smallrye/faulttolerance/api/FaultTolerance.java
doc/modules/ROOT/pages/reference/programmatic-api.adoc
implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java
implementation/standalone/src/test/java/io/smallrye/faulttolerance/standalone/test/StandaloneMetricsTest.java
testsuite/basic/src/test/java/io/smallrye/faulttolerance/programmatic/CdiMetricsTest.java

The issue is that a random UUID is used as a value of the metrics tag `method` if the user doesn't set a description on `FaultTolerance`. These values are always held in memory, so in case more and more `FaultTolerance` objects without description are created, more and more memory is held.
The fix is relatively simple: in case no description is set (and a random UUID should be used), no metrics are emitted. This is technically a breaking change, but it's better to require users to explicitly state the value of the metrics tag than to leak memory.

[6.4] fix memory leak in metrics

---

implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceExtension.java

This is mostly for the JaCoCo coverage tool that we run automatically in CI, but also feels like the right thing to do in general.

skip intercepting synthetic methods

---

pom.xml
testsuite/tck/pom.xml

This commit intentionally stays on Jakarta EE 10 dependencies, but all others are updated to the latest.
OpenTelemetry is an exception: it is updated to the latest version supported by the latest version of MicroProfile Telemetry.

bump dependencies
